# Python CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: moregreenhouse/tm-base

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Does docker even exist
          command: docker -v
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: |
          docker run -d -p 3030:3030 stain/jena-fuseki

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt


      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest tests
  
      - store_artifacts:
          path: test-reports
          destination: test-reports
